'use strict';

const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { installAgentRules, installCodexSkill, installSkillDefaults, startMarker, endMarker } = require('./agent-rules');
const { analyzeCoverage } = require('./coverage');
const { initProject } = require('./init');
const { wireProject } = require('./wire');

const projectAgentRuleFiles = [
  'AGENTS.md',
  'CLAUDE.md',
  'GEMINI.md',
  path.join('.cursor', 'rules', 'execfence.mdc'),
  path.join('.github', 'copilot-instructions.md'),
  path.join('.continue', 'rules', 'execfence.md'),
  path.join('.windsurf', 'rules', 'execfence.md'),
  path.join('.aider', 'execfence.md'),
  path.join('.roo', 'rules', 'execfence.md'),
  '.clinerules',
];

const packageScriptsToUnwrap = [
  'test',
  'build',
  'dev',
  'start',
  'pack',
  'publish',
  'preinstall',
  'install',
  'postinstall',
  'prepare',
  'prepack',
  'postpack',
  'prepublishOnly',
];

function guardStatus(cwd = process.cwd()) {
  const root = path.resolve(cwd);
  const coverage = analyzeCoverage(root);
  const protectedCount = coverage.entrypoints.filter((entry) => entry.guarded).length;
  const ci = ciStatus(root);
  return {
    cwd: root,
    ok: coverage.uncovered.length === 0 && hasProjectAgentRules(root).ok && (!ci.applicable || ci.hasExecFenceCi) && reportsGitignored(root),
    entrypoints: {
      total: coverage.entrypoints.length,
      protected: protectedCount,
      unprotected: coverage.uncovered.length,
      items: coverage.entrypoints,
      unprotectedItems: coverage.uncovered,
    },
    agentRules: hasProjectAgentRules(root),
    ci,
    reportsGitignore: {
      ok: reportsGitignored(root),
      file: path.join(root, '.gitignore'),
    },
  };
}

function guardPlan(cwd = process.cwd()) {
  const root = path.resolve(cwd);
  return {
    cwd: root,
    dryRun: true,
    steps: [
      'init --preset auto',
      'coverage',
      'wire --apply',
      'install-agent-rules --scope project',
      'guard status',
    ],
    init: initProject({ cwd: root, preset: 'auto', dryRun: true }),
    coverage: analyzeCoverage(root),
    wiring: wireProject(root, { dryRun: true }),
    agentRules: plannedProjectAgentRules(root),
    status: guardStatus(root),
  };
}

function guardEnable(cwd = process.cwd(), options = {}) {
  const root = path.resolve(cwd);
  if (!options.apply) {
    return guardPlan(root);
  }
  const before = guardStatus(root);
  const init = initProject({ cwd: root, preset: 'auto', dryRun: false });
  const coverageBeforeWire = analyzeCoverage(root);
  const wiring = wireProject(root, { dryRun: false });
  const agentRules = installAgentRules({ scope: 'project', project: root });
  const after = guardStatus(root);
  return {
    cwd: root,
    dryRun: false,
    ok: after.ok,
    before,
    init,
    coverageBeforeWire,
    wiring,
    agentRules,
    status: after,
  };
}

function guardDisable(cwd = process.cwd()) {
  const root = path.resolve(cwd);
  const changes = [
    ...disablePackageScripts(root),
    ...disableWorkflows(root),
    ...disableMakefile(root),
    ...disableVscodeTasks(root),
    ...removeProjectAgentRules(root),
  ];
  return {
    cwd: root,
    ok: true,
    changes,
    preserved: [
      '.execfence/reports/',
      '.execfence/config/',
      '.execfence/trust/',
      '.execfence/cache/',
      '.execfence/quarantine/',
    ],
    manualReview: [
      'Review .execfence/config/* if the project no longer needs ExecFence policy files.',
      'Review CI workflows for custom guardrail edits not generated by ExecFence.',
    ],
    status: guardStatus(root),
  };
}

function guardGlobalStatus(options = {}) {
  const home = path.resolve(options.home || os.homedir());
  const codexHome = path.resolve(options.codexHome || path.join(home, '.codex'));
  const globalRuleFiles = [
    path.join(home, '.codex', 'AGENTS.md'),
    path.join(home, '.claude', 'CLAUDE.md'),
    path.join(home, '.gemini', 'GEMINI.md'),
  ];
  const defaultsPath = path.join(home, '.agents', 'skills', 'execfence', 'defaults.json');
  const skillPath = path.join(codexHome, 'skills', 'execfence', 'SKILL.md');
  return {
    home,
    codexHome,
    ok: fs.existsSync(defaultsPath) && fs.existsSync(skillPath) && globalRuleFiles.every(hasExecFenceMarker),
    defaults: { filePath: defaultsPath, exists: fs.existsSync(defaultsPath) },
    codexSkill: { filePath: skillPath, exists: fs.existsSync(skillPath) },
    agentRules: globalRuleFiles.map((filePath) => ({
      filePath,
      exists: fs.existsSync(filePath),
      hasRule: hasExecFenceMarker(filePath),
    })),
    shellInterception: {
      enabled: false,
      note: 'ExecFence does not alter PATH, aliases, shims, or shell profiles in global mode.',
    },
  };
}

function guardGlobalEnable(options = {}) {
  const home = path.resolve(options.home || os.homedir());
  const codexHome = path.resolve(options.codexHome || path.join(home, '.codex'));
  const installed = installCodexSkill({ codexHome });
  const defaults = installSkillDefaults({ home });
  const rules = installAgentRules({ scope: 'global', home });
  return {
    home,
    codexHome,
    ok: true,
    installed,
    defaults,
    rules,
    shellInterception: {
      enabled: false,
      note: 'No PATH, alias, shim, npm, go, python, cargo, make, or shell profile interception was installed.',
      optionalManualUsage: [
        'Use npx --yes execfence guard enable --apply inside each project.',
        'Use npx --yes execfence run -- <command> for one-off guarded execution.',
      ],
    },
    status: guardGlobalStatus({ home, codexHome }),
  };
}

function hasProjectAgentRules(cwd) {
  const files = projectAgentRuleFiles.map((file) => {
    const filePath = path.join(cwd, file);
    return {
      file,
      filePath,
      exists: fs.existsSync(filePath),
      hasRule: hasExecFenceMarker(filePath),
    };
  });
  return {
    ok: files.every((file) => file.exists && file.hasRule),
    files,
  };
}

function plannedProjectAgentRules(cwd) {
  return {
    scope: 'project',
    files: projectAgentRuleFiles.map((file) => ({
      file,
      filePath: path.join(cwd, file),
      action: fs.existsSync(path.join(cwd, file)) ? 'update marked ExecFence block' : 'create with ExecFence rule',
    })),
  };
}

function ciStatus(cwd) {
  const workflows = path.join(cwd, '.github', 'workflows');
  if (!fs.existsSync(workflows)) {
    return { applicable: false, hasExecFenceCi: false, workflowFiles: [] };
  }
  const workflowFiles = fs.readdirSync(workflows)
    .filter((file) => /\.ya?ml$/i.test(file))
    .map((file) => path.join('.github', 'workflows', file).replaceAll(path.sep, '/'));
  return {
    applicable: workflowFiles.length > 0,
    hasExecFenceCi: workflowFiles.some((file) => /execfence\s+ci|bin\/execfence\.js\s+ci/.test(fs.readFileSync(path.join(cwd, file), 'utf8'))),
    workflowFiles,
  };
}

function reportsGitignored(cwd) {
  const gitignore = path.join(cwd, '.gitignore');
  return fs.existsSync(gitignore) && /\.execfence\/reports\//.test(fs.readFileSync(gitignore, 'utf8'));
}

function hasExecFenceMarker(filePath) {
  return fs.existsSync(filePath) && new RegExp(escapeRegExp(startMarker)).test(fs.readFileSync(filePath, 'utf8'));
}

function disablePackageScripts(cwd) {
  const filePath = path.join(cwd, 'package.json');
  if (!fs.existsSync(filePath)) {
    return [];
  }
  const pkg = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  const scripts = pkg.scripts || {};
  const changes = [];
  for (const name of packageScriptsToUnwrap) {
    if (typeof scripts[name] !== 'string') {
      continue;
    }
    const next = unwrapCommand(scripts[name]);
    if (next !== scripts[name]) {
      changes.push(change('package-json-script', 'package.json', name, scripts[name], next));
      scripts[name] = next;
    }
  }
  for (const hook of ['prestart', 'prebuild', 'pretest', 'prewatch']) {
    if (typeof scripts[hook] === 'string' && scripts[hook].startsWith('npm run execfence:scan && ')) {
      const next = scripts[hook].replace(/^npm run execfence:scan &&\s*/, '');
      changes.push(change('package-json-script', 'package.json', hook, scripts[hook], next));
      scripts[hook] = next;
    }
  }
  for (const aux of ['execfence:ci', 'execfence:scan']) {
    if (scripts[aux] === 'execfence ci' || scripts[aux] === 'execfence scan') {
      changes.push(change('package-json-script', 'package.json', aux, scripts[aux], null));
      delete scripts[aux];
    }
  }
  if (changes.length) {
    pkg.scripts = scripts;
    fs.writeFileSync(filePath, `${JSON.stringify(pkg, null, 2)}\n`);
  }
  return changes;
}

function disableWorkflows(cwd) {
  const workflows = path.join(cwd, '.github', 'workflows');
  if (!fs.existsSync(workflows)) {
    return [];
  }
  const changes = [];
  for (const file of fs.readdirSync(workflows).filter((name) => /\.ya?ml$/i.test(name))) {
    const filePath = path.join(workflows, file);
    const rel = path.join('.github', 'workflows', file).replaceAll(path.sep, '/');
    const original = fs.readFileSync(filePath, 'utf8');
    const next = original.replace(/^(\s*-\s*run:\s*)execfence\s+run\s+--\s*(.+)$/gm, (full, prefix, command) => {
      changes.push(change('workflow-run', rel, command, full.trim(), `${prefix}${command}`.trim()));
      return `${prefix}${command}`;
    });
    if (next !== original) {
      fs.writeFileSync(filePath, next);
    }
  }
  return changes;
}

function disableMakefile(cwd) {
  const filePath = path.join(cwd, 'Makefile');
  if (!fs.existsSync(filePath)) {
    return [];
  }
  const original = fs.readFileSync(filePath, 'utf8');
  let next = original;
  const changes = [];
  next = next.replace(/^(build|test|dev|run|pack|publish|test-race|vet):\s+guard([^\r\n]*)$/gm, (full, target, deps) => {
    const replacement = `${target}:${deps}`;
    changes.push(change('make-target', 'Makefile', target, full, replacement));
    return replacement;
  });
  if (/\n?guard:\r?\n\t(?:npx --yes )?execfence scan\r?\n?/.test(next)) {
    next = next.replace(/\n?guard:\r?\n\t(?:npx --yes )?execfence scan\r?\n?/g, '\n');
    changes.push(change('make-target', 'Makefile', 'guard', 'guard target', null));
  }
  next = next.replace(/(\.PHONY:[^\r\n]*)/g, (line) => line.replace(/\s+guard\b/, ''));
  if (next !== original) {
    fs.writeFileSync(filePath, next.endsWith('\n') ? next : `${next}\n`);
  }
  return changes;
}

function disableVscodeTasks(cwd) {
  const filePath = path.join(cwd, '.vscode', 'tasks.json');
  if (!fs.existsSync(filePath)) {
    return [];
  }
  let parsed;
  try {
    parsed = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  } catch {
    return [];
  }
  const changes = [];
  for (const task of parsed.tasks || []) {
    if (typeof task.command !== 'string') {
      continue;
    }
    const next = unwrapCommand(task.command);
    if (next !== task.command) {
      changes.push(change('vscode-task', '.vscode/tasks.json', task.label || next, task.command, next));
      task.command = next;
    }
  }
  if (changes.length) {
    fs.writeFileSync(filePath, `${JSON.stringify(parsed, null, 2)}\n`);
  }
  return changes;
}

function removeProjectAgentRules(cwd) {
  const changes = [];
  for (const file of projectAgentRuleFiles) {
    const filePath = path.join(cwd, file);
    const removed = removeMarkedBlock(filePath);
    if (removed.changed) {
      changes.push(change('agent-rule', file, file, 'ExecFence marked rule', removed.deleted ? null : 'removed marked ExecFence rule'));
    }
  }
  return changes;
}

function removeMarkedBlock(filePath) {
  if (!fs.existsSync(filePath)) {
    return { filePath, changed: false, deleted: false };
  }
  const existing = fs.readFileSync(filePath, 'utf8');
  const pattern = new RegExp(`${escapeRegExp(startMarker)}[\\s\\S]*?${escapeRegExp(endMarker)}\\s*`, 'g');
  if (!pattern.test(existing)) {
    return { filePath, changed: false, deleted: false };
  }
  const next = existing.replace(pattern, '').trim();
  if (!next || /^---\s*description:[\s\S]*?---\s*$/.test(next)) {
    fs.unlinkSync(filePath);
    return { filePath, changed: true, deleted: true };
  }
  fs.writeFileSync(filePath, `${next}\n`);
  return { filePath, changed: true, deleted: false };
}

function unwrapCommand(command) {
  return String(command).replace(/^execfence\s+run\s+--\s*/, '');
}

function change(type, file, name, before, after) {
  return { type, file, name, before, after };
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

module.exports = {
  guardDisable,
  guardEnable,
  guardGlobalEnable,
  guardGlobalStatus,
  guardPlan,
  guardStatus,
};
